[package]
name = "mobile"
version = "0.2.5"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }

[features]
default = []
mobile = ["dioxus/mobile"]
server = ["dioxus/server"]
